# Site settings
title: Belarusan Discourse and Content
description: Plain language makes it easier for the public to read, understand, and use government communications.
email: adresse@bidon.fr
image: /assets/img/twitter_profile.png
facebook: 
twitter: 
pinterest: 
linkedin: 
instagram: 
github:
  organization: discoinstitute
  repository: bel.disco.institute
  default_branch: master

sitewide_notification:
  display: true
  heading: Information Status
  text: >-
    In light of OPM guidance and increasing concerns about COVID-19 (coronavirus), we are suspending accepting training requests.


theme: uswds-jekyll
url: "https://bel.disco.institute/" # the base hostname & protocol for your site
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - CONTRIBUTING.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - webpack.config.js

keep_files:
  - /assets/js/build/bundle.js

scripts:
  - /assets/js/build/bundle.js
  - /assets/uswds/js/uswds.min.js

styles:
  - href: /assets/css/main.css
    media: screen, print

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

defaults:
  - scope:
      path: "assets/uswds"
    values:
      skip_index: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"
  - scope:
      path: "_pages/guidelines"
    values:
      pagination: true

collections:
  pages:
    output: true
    permalink: /:path/

kramdown:
  parse_block_html: true

jekyll_pages_api_search:
  skip_index: false
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
  results_page_title: Search results
